-- PO 작성 알림 인박스 (이슈 #79): HQ_STAFF가 PO 작성 시 HQ_MANAGER에게만 알림.
-- 서비스 내 완결(로컬 INSERT) — Kafka/outbox/processed_event 불필요(단일 트랜잭션 멱등).
CREATE TABLE po_notification (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_role VARCHAR(20)  NOT NULL,            -- 'HQ_MANAGER'
    po_number   VARCHAR(20)  NOT NULL,            -- 클릭 시 이동 대상
    message     VARCHAR(255) NOT NULL,
    read        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_by  BIGINT,                           -- 작성자 사번(참고용)
    created_at  TIMESTAMP    NOT NULL DEFAULT now()
);

-- 인박스 조회(역할별 미읽음 최신순) 인덱스
CREATE INDEX idx_po_notification_inbox ON po_notification (target_role, read, id DESC);

COMMENT ON TABLE  po_notification             IS 'PO 작성 알림 인박스 (매니저 전용 read-model)';
COMMENT ON COLUMN po_notification.target_role IS '수신 대상 역할 — 현재 HQ_MANAGER 고정';
COMMENT ON COLUMN po_notification.po_number   IS '연관 PO 번호 — 클릭 시 상세로 이동';
COMMENT ON COLUMN po_notification.read        IS '읽음 여부 — 서버는 미읽음만 반환';
